### ISSUE TITLE
Column `cols` must be length 1 (the number of rows), not 3 while running Summarize

### ISSUE THREAD

**Issue by athulmenon** [mcanouil/NACHO#15]
Please briefly describe your problem and what output you expect. If you have a question, please don't use this form. Instead, ask on <https://stackoverflow.com/> or <https://community.rstudio.com/>.

Please include a minimal reproducible example (AKA a reprex). If you've never heard of a [reprex](https://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>.

---
Hi,

Tried to run NACHO as mentioned in the supplementary file. Data from GEO is downloaded and Samplesheet.csv is also generated. But once I am using Summarize function it shows "Error: Column `cols` must be length 1 (the number of rows), not 3". The reprex() shows different error.
Thanks in advance.
Athul

```r
nacho <-summarize(data_directory =paste0(getwd(), "/GSE70970"),ssheet_csv =paste0(getwd(), "/GSE70970/Samplesheet.csv"),id_colname = "IDFILE",housekeeping_predict = TRUE, normalisation_method = "GEO",n_comp = 10)
#> Error in summarize(data_directory = paste0(getwd(), "/GSE70970"), ssheet_csv = paste0(getwd(), : could not find function "summarize"
```

**Comment by mcanouil** [comment]
Hi,

thanks for using NACHO, please refer to #12 

Best regards !
Mickaël

**Comment by mcanouil** [comment]
Hi,

In response to https://github.com/mcanouil/NACHO/issues/12#issuecomment-559348280
Could you run the reproducible examples provided in a new R session ?

**Comment by athulmenon** [comment]
Hi Mcanouil,

Restarted R and tried to run the code fresh again. Still the same error!
`> GSE70970_sum <- summarize(

    data_directory = paste0(tempdir(), "/GSE70970/Data"), # Where the data is

    ssheet_csv = targets, # The samplesheet

    id_colname = "IDFILE", # Name of the column that contains the identfiers

    housekeeping_genes = NULL, # Custom list of housekeeping genes

    housekeeping_predict = TRUE, # Predict the housekeeping genes based on the data?

    normalisation_method = "GEO", # Geometric mean or GLM

    n_comp = 5 # Number indicating the number of principal components to compute. 

    )`

Error goes like this : [NACHO] Importing RCC files. Error: Column cols must be length 1 (the number of rows), not 3

Any other solutions?
Thanks for quick response.

Athul
