### ISSUE TITLE
Provide easy means to export normalized Counts

### ISSUE THREAD

**Issue by apeltzer** [mcanouil/NACHO#17]
Thanks for creating this tool / method!  The Shiny App / general functionality is really an improvement and works pretty good. However, I'd like to export the data (e.g. normalized counts) to a separate TSV/CSV file to do downstream analyses with it, which is currently not very straightforward. 

It would be very nice to see an export functionality - either in the Shiny App or (also good) in the R package in general. Couldn't find anything unfortunately...

**Comment by mcanouil** [comment]
Hi,

I described how to export the counts matrix within the vignette focusing on analysis.
https://mcanouil.github.io/NACHO/articles/NACHO-analysis.html

``` r
expr_counts <- GSE70970[["nacho"]] %>% 
  filter(grepl("Endogenous", CodeClass)) %>% 
  select(IDFILE, Name, Count_Norm) %>% 
  pivot_wider(names_from = "Name", values_from = "Count_Norm") %>% # "Name" can be replaced with "Accession"
  column_to_rownames("IDFILE") %>% 
  t()
```
The code above could end up in a function like the following one (quick draft).
``` r
library(NACHO)
get_counts <- function(nacho, codeclass = "Endogenous", rownames = c("Name", "Accession"), colnames = "IDFILE") {
  nacho[["nacho"]] %>% 
    dplyr::filter(grepl(codeclass, .data[["CodeClass"]])) %>% 
    dplyr::select(IDFILE, Name, Count_Norm) %>% 
    tidyr::pivot_wider(names_from = rownames[1], values_from = "Count_Norm") %>% # "Name" can be replaced with "Accession"
    tibble::column_to_rownames(colnames) %>% 
    t()
}
get_counts(GSE74821)
```

**Comment by apeltzer** [comment]
Ok, didn't see / find this intuitively - this looks great, thank you!

**Comment by apeltzer** [comment]
Could be potentially cool to have some exporting functionality in the Shiny Applicaiton but from the commandline this is more than I expected and I'm absolutely happy with this 👍

**Comment by mcanouil** [comment]
I'll think more about adding a function to ease the exportation and in that case, I'll probably add some download button using that function.

The function defined above, does not exclude bad samples nor bad "genes".
Extra filters should be applied based on quality columns, this is why I did not implement such function, because it will have a lot of parameters for QC.

**Comment by apeltzer** [comment]
Thats a valid and good concern. Thank you for the insights / comments. I do think there would be a benefit to allow this export, but also see the concerns here!
