### ISSUE TITLE
Documentation / Interface Mismatch

### ISSUE THREAD

**Issue by apeltzer** [mcanouil/NACHO#18]
Hi!

the documentation for `normalize()` suggests that the function creates a list of normalized counts etc pp - however, I only get a Nacho Object back (which is fine but different than expected given the documentation). Maybe this is a relict?

**Comment by mcanouil** [comment]
Hi,

yes, it is indeed a relict from previous versions.
Since the matrices were duplicates of what's inside "nacho" field, it increases the object size for no reason.
