### ISSUE TITLE
Background normalization?

### ISSUE THREAD

**Issue by apeltzer** [mcanouil/NACHO#22]
Does NACHO provide / perform Background normalization methods / functionality via Background subtraction or thresholding? I just saw the normalization methods available when running `load_rcc` and `normalize()` but these seem not to include such a normalization approach.

**Comment by mcanouil** [comment]
The normalisation methods `GEO`or `GLM` are used to compute the normalisation factors for positive and housekeeping probes.
They also used to compute the "negative factor" (poor naming choice though): "geometric mean" (`GEO`) or the corresponding value from `GLM` of negative probes.

To summarise *NACHO* computes a `data.frame` with three columns:
* "Positive_factor"
* "Negative_factor"
* "House_factor" (not necessarily used)

The simple formula for the normalisation is:
(Count_i - geo(Negative_i)) * PositiveF (with PositiveF: mean(geo(Positive)) / geo(Positive_i))
or 
(Count - Negative) * PositiveF * HousekeepingF
In addition negative counts are replaced with `0`.

For short, background is taken into account.
Although, you can add additional threshold to be more "biologically relevant".
