### ISSUE TITLE
Pos and neg controls in RCC file

### ISSUE THREAD

**Issue by ChadAHighfill** [mcanouil/NACHO#32]
Please include a minimal reproducible example (AKA a reprex). If you've never heard of a [reprex](https://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>.

---

Hey Nacho team, when reading in my RCC files, each one harbors the internal positive and negative controls, labeled POS and NEG. How does this affect the predict housekeeping genes?

```r
# insert reprex here
```

**Comment by mcanouil** [comment]
POS/NEG are used to normalise the data at a more technical level. This includes housekeeping genes.

Housekeeping genes are used (when available through NanoString panel or "prediction") to normalise the data at a "biological level".

**Comment by ChadAHighfill** [comment]
Hi Mcanouil, this means, that the POS/NEG labels would not influence the predicted housekeeping genes?

**Comment by mcanouil** [comment]
POS/NEG are technical controls with know concentrations of biological materials, thus has nothing to do with your biological samples and/or housekeeping genes.
Their sole purpose is to be used to correct technical bias that might arise.
