### ISSUE TITLE
Differing Values in QC plots 

### ISSUE THREAD

**Issue by christopher-mohr** [mcanouil/NACHO#45]
Please include a minimal reproducible example (AKA a reprex). If you've never heard of a [reprex](https://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>.

---

Hi, I observed differences in the values in the QC plots like the ``BD` plot on repeated execution. See the code below that was executed multiple times. 

```r
library(NACHO)

# load RCC files
nacho_data <- load_rcc(data_directory = input_rcc_path,
                       ssheet_csv = input_samplesheet,
                       id_colname = "RCC_FILE_NAME")

plot_bd <- autoplot(
  object = nacho_data,
  x = "BD",
  colour = "CartridgeID",
  size = 0.5,
  show_legend = TRUE
)
```
I guess this might be due to the use of `position_jitter(width = 0.25)` in `auto_plot`. https://github.com/mcanouil/NACHO/blob/7784ecd93019375681a5ac833538502a2ecd08cf/R/autoplot.R#L328 
Although a horizontal shift of the data points might be desirable, the default value of the `height` parameter (seems to be `NULL`) seems to have an effect and shift the data points verrtically as well. 

This difference can be observed executing the code below.

```r
library(ggplot2)

jitter <- position_jitter(width = 0.1)
ggplot(mtcars, aes(am, vs)) +
  geom_point(position = jitter)

jitter2 <- position_jitter(width = 0.1, height = 0.0)
ggplot(mtcars, aes(am, vs)) +
  geom_point(position = jitter2)
```

<img width="730" alt="2023-08-04_16-49-08" src="https://github.com/mcanouil/NACHO/assets/6513088/855eab93-7edf-4ee0-abe4-5e2fa9ce2036">
<img width="733" alt="2023-08-04_16-49-25" src="https://github.com/mcanouil/NACHO/assets/6513088/0f8fb43d-8f86-40e9-b482-f86737cf6d88">

I guess this is not expected. Please let me know if you need more information.

**Comment by mcanouil** [comment]
Thanks for the well detailed report.
CRAN is currently closed for holidays, I'll try to submit a patch in the coming weeks.

**Comment by christopher-mohr** [comment]
> Thanks for the well detailed report. CRAN is currently closed for holidays, I'll try to submit a patch in the coming weeks. The patch should be on the `main` branch soon.

Thanks a lot for the quick fix. :)

**Comment by mcanouil** [comment]
FYI, I just submitted v2.0.5 to CRAN.
Hopefully up in few days up to week since CRAN just reopened.

**Comment by mcanouil** [comment]
It's on CRAN (<https://cran.r-project.org/package=NACHO>).
Just have to wait until all packages are built/complied by CRAN.
