### ISSUE TITLE
Question about R^2 values in positive control linearity QC

### ISSUE THREAD

**Issue by neslihanky** [mcanouil/NACHO#48]
Hi, 

Thank you for the great tool. I have a question on calculation of the positive control linearity QC. Based on NACHO's QC plot output and Nanostring's guide it should be "R^2 value". When I looked at the calculation function for this metric, it is actually calculating Pearson's correlation coefficient [here ](https://github.com/mcanouil/NACHO/blob/main/R/qc_positive_control.R). Just wanted to ask if you are aware of this or am I missing a point?  

Thank you!

**Comment by mcanouil** [comment]
I must say, I don't recall as it's from 4/5 years ago and I did not write all the code.

From the unit (https://github.com/mcanouil/NACHO/blob/e2999983adc0038d448caf816f2715ef42f024fd/R/autoplot.R#L260) it seems, the computation is indeed wrong.
I'll fix and release soon as CRAN is back after the holidays.
Thanks for the report!

**Comment by neslihanky** [comment]
Thanks for the quick response on this!

**Comment by mcanouil** [comment]
I should be able to make the release this week and should be available soon after that.
