### ISSUE TITLE
excluding POS_F from positive control linearity calculation

### ISSUE THREAD

**Issue by neslihanky** [mcanouil/NACHO#51]
Hi,

Thank you for your efforts again. Was the positive control F (POS_F) included in positive control linearity calculation? 

Based on the code [here](https://github.com/mcanouil/NACHO/blob/7c2b47df9c10e7d263101f20a81e017bbfefba1c/R/qc_features.R#L17) it seems like all positive probes were used. Nanostring suggests excluding POS_F from this calculation since it is below the limit of detection. Here is the related part in [nanostring documentation](https://nanostring.com/wp-content/uploads/Gene_Expression_Data_Analysis_Guidelines.pdf):

"Note that because POS_F has a known concentration of 0.125 fM, which is considered below the limit of detection of the system, it should be excluded from this calculation (although you will see that POS_F counts are significantly higher than the negative control counts in most cases)."

Thank you!

**Comment by mcanouil** [comment]
Yes, it is:

- https://github.com/mcanouil/NACHO/blob/7c2b47df9c10e7d263101f20a81e017bbfefba1c/R/factor_calculation.R#L22
